[store]
dir = "target/nextest"


[profile.default]
retries = { backoff = "exponential", count = 3, delay = "3s" }
test-threads = "num-cpus"
threads-required = 1
status-level = "all"
final-status-level = "fail"
failure-output = "final"
success-output = "never"
fail-fast = false
slow-timeout = { period = "30s" }
leak-timeout = "100ms"


[profile.default.junit]
path = "out/junit.xml"
report-name = "nextest-run"
store-success-output = true
store-failure-output = true

[profile.ci]
# Don't fail fast in CI to run the full test suite.
fail-fast = false

[profile.ci.junit]
path = 'junit.xml'
